name: feature_home
description: feature - home
publish_to: 'none'

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  bloc: ^8.1.1
  cupertino_icons: ^1.0.2
  core_bloc:
    path: ../../core/bloc
  core_data:
    path: ../../core/data
  core_common:
    path: ../../core/common
  core_designsystem:
    path: ../../core/designsystem
  core_ui:
    path: ../../core/ui
  equatable: ^2.0.5
  go_router: ^6.2.0
  flutter_bloc: ^8.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - '../../../graphics/'