name: Bridge
repository: https://github.com/yaroslav-android/Bridge

packages:
  - packages/feature/*
  - packages/core/*
  - tests

command:
  bootstrap:
    # It seems so that running "pub get" in parallel has some issues (like
    # https://github.com/dart-lang/pub/issues/3404). Disabling this feature
    # makes the CI much more stable.
    runPubGetInParallel: false
    usePubspecOverrides: true

scripts:
  format:
    run: |
      dart format --fix .
    description: |
      Format all files with Dart Format.
  gen:
    run: |
      cd $MELOS_ROOT_PATH/packages/core/network && \
      flutter pub run build_runner build --delete-conflicting-outputs
    description: |
      Generates dart files for Json library.
  gen:auto:
    run: |
      cd $MELOS_ROOT_PATH/packages/core/network && \
      flutter pub run build_runner watch --delete-conflicting-outputs
    description: |
      Same as `gen` but automated.