name: core_network
description: core - network
publish_to: 'none'

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  common:
    path: ../common
  flutter:
    sdk: flutter
  json_annotation: ^4.8.0
  http: ^0.13.5

dev_dependencies:
  build_runner: ^2.3.3
  very_good_analysis: ^4.0.0
  json_serializable: ^6.6.0
