name: bridge
description: Bridge game for Android and iOS
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  bloc: ^8.1.1
  core_bloc:
    path: packages/core/bloc
  core_data:
    path: packages/core/data
  core_model:
    path: packages/core/model
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  go_router: ^6.2.0
  feature_home:
    path: packages/feature/home
  feature_onboarding:
    path: packages/feature/onboarding
  feature_lobby:
    path: packages/feature/lobby
  feature_login:
    path: packages/feature/login
  feature_signup:
    path: packages/feature/signup
  feature_room_list:
    path: packages/feature/room_list
  flutter_bloc: ^8.1.2
  flutter:
    sdk: flutter
  formz: ^0.5.0+1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  melos: ^3.0.0
  mockito: ^5.4.0

  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - 'graphics/'

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
