name: CI build
on: 
  workflow_call:
    inputs:
      analyze_directories: "lib"
  pull_request
  

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      working_directory: "./bridge"