name: CI build
on: 
  pull_request:
  workflow_call:
    inputs:
      username:
        description: 'override to run only lib without test folder'
        default: 'lib'
        required: false
        type: string
  

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      working_directory: "./bridge"