name: CI build
on: 
  pull_request:
  workflow_call:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string
  

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    inputs:
      analyze_directories: "lib"
    with:
      working_directory: "./bridge"